
services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    container_name: datadog-agent
    env_file: .env
    environment:
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOG_LEVEL=debug
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    ports:
      - "8126:8126"
      - "8125:8125"
  datablog:
    container_name: datablog
    restart: always
    build: .
    env_file: .env
    labels: 
       com.datadoghq.tags.env: development
       com.datadoghq.tags.service: datablog
       com.datadoghq.tags.version: "2.0.0"
       com.datadoghq.ad.logs: '[{"source": "node", "service": "datablog"}]'
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DOCKER=true
      - DD_TRACE_AGENT_PORT=8126
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
      datadog-agent:
        condition: service_started
  mongo:
    container_name: mongo
    image: mongo:7.0
    labels: 
       com.datadoghq.tags.env: development
       com.datadoghq.tags.service: datablog-mongo
    # Allow optional runtime tuning via MONGO_OPTS, e.g. "--nojournal --wiredTigerCacheSizeGB=0.25"
    command: bash -lc "exec mongod --bind_ip_all ${MONGO_OPTS}"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 }).ok' || mongo --eval 'db.runCommand({ ping: 1 }).ok'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    # Persistent data to avoid filling container layer and immediate shutdowns
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-data:
