name: Nikto Scan

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  nikto:
    name: Nikto Web Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      - name: Prepare .env for docker-compose
        run: |
          if [ ! -f .env ]; then
            if [ -f .env.example ]; then
              cp .env.example .env
            else
              cat > .env <<EOF
DD_SITE=datadoghq.com
DD_API_KEY=DUMMY
DD_CLIENT_TOKEN=dummy
DD_APPLICATION_ID=dummy
DD_SERVICE=datablog
DD_ENV=ci
DD_VERSION=2.0.0
EOF
            fi
          fi

      - name: Start stack (app + mongo)
        run: |
          docker compose -f docker-compose.yml up -d --build app mongo
          for i in {1..60}; do
            if curl -sf http://localhost:3000 >/dev/null; then echo "app up"; break; fi; sleep 2; done

      - name: Run Nikto scan
        run: |
          docker run --rm --network host frapsoft/nikto -h http://127.0.0.1:3000 -o nikto.txt

      - name: Upload Nikto results
        uses: actions/upload-artifact@v4
        with:
          name: nikto-results
          path: nikto.txt

      - name: Stop stack
        if: always()
        run: |
          docker compose -f docker-compose.yml down -v
