name: Nikto Scan

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  nikto:
    name: Nikto Web Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'

      - name: Install dependencies
        run: npm ci

      - name: Start application
        run: |
          npm start &
          echo $! > app.pid
          sleep 8
        env:
          NODE_ENV: production

      - name: Run Nikto scan
        run: |
          docker run --rm --net=host sullo/nikto:2.5.0 -h http://127.0.0.1:3000 -o nikto.txt

      - name: Upload Nikto results
        uses: actions/upload-artifact@v4
        with:
          name: nikto-results
          path: nikto.txt

      - name: Stop application
        if: always()
        run: |
          kill $(cat app.pid) || true

