name: NodeJSSCAN (SAST)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  njsscan:
    name: Static Analysis (njsscan)
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run njsscan
        uses: ajinabraham/njsscan-action@v7
        with:
          args: "--sarif --output njsscan.sarif ."

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: njsscan.sarif

