name: Node.js CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  # Lint and Format Check
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

      - name: Run ESLint (CI - no warnings)
        run: npm run lint:ci

      - name: Check Prettier formatting
        run: npm run format:check

  # Unit and Integration Tests
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24]
    
    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

      - name: Run unit tests
        run: npm test
        env:
          MONGODB_URI: mongodb://localhost:27017/datablog-test
          NODE_ENV: test

      - name: Audit dependencies (prod, high+) [informational]
        run: npm run audit:ci
        continue-on-error: true

  # Docker Build (for local dev/test)
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: datablog:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # End-to-End Tests with Playwright
  e2e:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: [test, docker-build]
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-jammy
      options: --ipc=host
    
    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Ensure .env exists for app
        run: |
          if [ ! -f .env ]; then
            if [ -f .env.example ]; then cp .env.example .env; else echo "DD_SITE=datadoghq.com" > .env; fi
          fi

      
      - name: Start application
        run: |
          npm start &
          for i in {1..60}; do
            if curl -sf http://localhost:3000 >/dev/null; then echo "app up"; break; fi; sleep 2; done
        env:
          NODE_ENV: test
          MONGODB_URI: mongodb://mongodb:27017/datablog-e2e

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  
