name: Secret Scan

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Gitleaks (container)
        run: |
          docker run --rm \
            -v "$PWD":/repo \
            -w /repo \
            zricethezav/gitleaks:latest \
            detect --source /repo --report-format sarif --report-path /repo/gitleaks.sarif --redact

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
