name: Secret Scan

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Gitleaks (container)
        run: |
          docker run --rm \
            -v "$PWD":/repo \
            -w /repo \
            zricethezav/gitleaks:latest \
            detect --source /repo --report-format sarif --report-path /repo/gitleaks.sarif --redact

      - name: Ensure SARIF exists (gitleaks)
        if: always()
        shell: bash
        run: |
          if [ ! -f gitleaks.sarif ]; then
            printf '%s\n' \
              '{' \
              '  "$schema": "https://json.schemastore.org/sarif-2.1.0.json",' \
              '  "version": "2.1.0",' \
              '  "runs": [' \
              '    {' \
              '      "tool": { "driver": { "name": "gitleaks" } },' \
              '      "results": []' \
              '    }' \
              '  ]' \
              '}' > gitleaks.sarif
          fi

      - name: Upload SARIF (gitleaks)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif

      - name: Summarize gitleaks findings
        if: always()
        shell: bash
        run: |
          if command -v jq >/dev/null 2>&1; then
            COUNT=$(jq '[.runs[]?.results[]] | length' gitleaks.sarif 2>/dev/null || echo 0)
          else
            COUNT=unknown
          fi
          {
            echo "### Gitleaks Secret Scan"
            echo "SARIF uploaded from: gitleaks.sarif"
            echo "Findings count: ${COUNT}"
          } >> "$GITHUB_STEP_SUMMARY"
