name: ZAP Baseline Scan

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  zap:
    name: OWASP ZAP Baseline
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: datablog:test

      - name: Run container
        run: |
          docker run -d --name app -p 3000:3000 -e NODE_ENV=production datablog:test
          for i in {1..30}; do
            if curl -sf http://localhost:3000 >/dev/null; then echo "app up"; break; fi; sleep 2; done

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Stop container
        if: always()
        run: |
          docker rm -f app || true
